### ISSUE TITLE
[RFC] Creare sezione slack

### ISSUE THREAD

**Issue by liuggio** [GrUSP/GrUSP.org#7]
sarebbe duopo dare amore e spingere slack http://slack-grusp.herokuapp.com/ 
vedo due possibilità
o metterla tra i social in basso nel footer
o creare una sezione dedicata 

cordiali saluti.

**Comment by fntlnz** [comment]
Si potrebbe anche usare il badge: https://github.com/rauchg/slackin#realtime-badge

**Comment by cesaredamico** [comment]
Aggiunto link nei social in basso... può andare? consigli su come migliorarlo?

**Comment by liuggio** [comment]
@cesaredamico mitico la chiudo...
